import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from '@react-pdf/renderer'
import type { EvidencePackRecord } from '../../lib/graphql/queries'

interface EvidencePackPdfProps {
  pack: EvidencePackRecord
}

function formatDate(value?: string | null): string {
  if (!value) return 'Not set'
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  }).format(new Date(value))
}

function formatDateTime(value?: string | null): string {
  if (!value) return 'Not set'
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(new Date(value))
}

function stringifySummary(value: unknown): string {
  if (!value) return 'No narrative summary recorded for this evidence pack.'
  if (typeof value === 'string') return value
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, entryValue]) => entryValue !== null && entryValue !== undefined && entryValue !== '')
      .map(([key, entryValue]) => `${key}: ${String(entryValue)}`)

    if (entries.length > 0) {
      return entries.join('\n')
    }
  }
  return String(value)
}

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontFamily: 'Helvetica',
    color: '#0f172a',
    backgroundColor: '#f8fafc',
    fontSize: 10,
    lineHeight: 1.5,
  },
  hero: {
    borderRadius: 16,
    padding: 18,
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#a7f3d0',
    marginBottom: 16,
  },
  eyebrow: {
    fontSize: 8,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: '#047857',
    marginBottom: 6,
    fontWeight: 700,
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    color: '#020617',
    marginBottom: 8,
  },
  body: {
    color: '#475569',
    fontSize: 10,
  },
  grid: {
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  metric: {
    flex: 1,
    borderRadius: 12,
    padding: 10,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  label: {
    color: '#64748b',
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  value: {
    color: '#020617',
    fontSize: 12,
    fontWeight: 700,
  },
  section: {
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#020617',
    fontSize: 14,
    fontWeight: 700,
    marginBottom: 8,
  },
  item: {
    paddingTop: 9,
    paddingBottom: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  itemTitle: {
    color: '#0f172a',
    fontSize: 11,
    fontWeight: 700,
  },
  itemMeta: {
    color: '#64748b',
    fontSize: 8,
    marginTop: 2,
  },
  itemDetail: {
    color: '#475569',
    fontSize: 9,
    marginTop: 4,
  },
  footer: {
    marginTop: 18,
    color: '#64748b',
    fontSize: 8,
  },
})

export function EvidencePackPdf({ pack }: EvidencePackPdfProps) {
  return (
    <Document
      title={`Oasis evidence pack ${pack.id}`}
      author="Oasis Care"
      subject="Inspection-ready evidence pack"
    >
      <Page size="A4" style={styles.page}>
        <View style={styles.hero}>
          <Text style={styles.eyebrow}>Oasis Care · Inspection-ready evidence</Text>
          <Text style={styles.title}>{pack.kind} evidence pack</Text>
          <Text style={styles.body}>
            This pack compiles recorded evidence for review. It supports governance and inspection preparation;
            it does not guarantee regulatory compliance outcomes.
          </Text>
        </View>

        <View style={styles.grid}>
          <View style={styles.metric}>
            <Text style={styles.label}>Status</Text>
            <Text style={styles.value}>{pack.status}</Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.label}>Period</Text>
            <Text style={styles.value}>
              {formatDate(pack.periodStart)} to {formatDate(pack.periodEnd)}
            </Text>
          </View>
          <View style={styles.metric}>
            <Text style={styles.label}>Evidence items</Text>
            <Text style={styles.value}>{pack.items.length}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Pack details</Text>
          <Text style={styles.body}>Person record: {pack.clientId}</Text>
          <Text style={styles.body}>Care plan record: {pack.carePlanId ?? 'Not linked'}</Text>
          <Text style={styles.body}>Generated by: {pack.generatedBy}</Text>
          <Text style={styles.body}>Generated at: {formatDateTime(pack.generatedAt)}</Text>
          <Text style={styles.body}>Published at: {formatDateTime(pack.publishedAt)}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Summary</Text>
          <Text style={styles.body}>{stringifySummary(pack.summary)}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Evidence timeline</Text>
          {pack.items.length === 0 ? (
            <Text style={styles.body}>No evidence items have been added to this pack yet.</Text>
          ) : (
            pack.items.map((item) => (
              <View key={item.id} style={styles.item}>
                <Text style={styles.itemTitle}>{item.headline}</Text>
                <Text style={styles.itemMeta}>
                  {item.sourceType} · {item.sourceId ?? 'manual'} · occurred {formatDateTime(item.occurredAt)}
                </Text>
                {item.detail && <Text style={styles.itemDetail}>{item.detail}</Text>}
              </View>
            ))
          )}
        </View>

        <Text style={styles.footer}>
          Generated by Oasis Care. Family-restricted and raw operational records should only be shared through
          approved, authorised routes.
        </Text>
      </Page>
    </Document>
  )
}
