export enum ErrorCode {
  // business
  VISIT_OVERLAP = 'VISIT_OVERLAP',
  VISIT_NOT_FOUND = 'VISIT_NOT_FOUND',
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  // medication
  MEDICATION_NOT_FOUND = 'MEDICATION_NOT_FOUND',
  MEDICATION_ADMINISTRATION_NOT_FOUND = 'MEDICATION_ADMINISTRATION_NOT_FOUND',
  MEDICATION_OVERLAP = 'MEDICATION_OVERLAP',
  // auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  FORBIDDEN_OWN_RESOURCE_ONLY = 'FORBIDDEN_OWN_RESOURCE_ONLY',
  FORBIDDEN_READ_ONLY = 'FORBIDDEN_READ_ONLY',
  FORBIDDEN_ADMIN_ONLY = 'FORBIDDEN_ADMIN_ONLY',
  FORBIDDEN_OFFICE_ACCESS = 'FORBIDDEN_OFFICE_ACCESS',
  INVALID_ROLE = 'INVALID_ROLE',
  // validation / system
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
