name: AWS key sanity check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-aws:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      # Configure creds from repo secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Quick identity check
      - name: Who am I?
        run: aws sts get-caller-identity
